version: 2

registries:
  composer:
    type: composer-repository
    url: https://composer.eneserk.de
    username: token
    password: ${{secrets.COMPOSER_TOKEN}}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # composer
  - package-ecosystem: "composer"
    directory: "./"
    registries:
      - composer
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
